#!/bin/bash
function create_local_var {
    local BEST="School"  # Create local variable BEST
    echo "Local variable BEST created with value: $BEST"
}
create_local_var  # Call the function' > create_best_var.sh
